# Generated by Django 2.2.10 on 2021-03-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20210308_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('iin', models.CharField(max_length=255)),
                ('doc1', models.CharField(max_length=255, null=True)),
                ('doc2', models.CharField(max_length=255, null=True)),
                ('doc3', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Insurance')),
            ],
        ),
    ]
