# Generated by Django 2.2.10 on 2021-03-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bday',
            field=models.DateTimeField(null=True),
        ),
    ]
