# Generated by Django 2.2.10 on 2021-03-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_issue_bday'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
            ],
        ),
    ]
