# Generated by Django 2.2.10 on 2021-03-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_typecar'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='typecar',
            old_name='city',
            new_name='name',
        ),
    ]
