# Generated by Django 2.2.10 on 2021-03-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='city',
            new_name='name',
        ),
    ]
