# Generated by Django 2.2.10 on 2021-05-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20210309_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
