# Generated by Django 2.2.10 on 2021-05-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_insurance_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
